// Regenerates cases/RECORDED.md: for every recorded case, the preferences resolved from the
// ENS text-record values and the exact instructions the model receives. No model call needed.
import { readFileSync, writeFileSync } from "node:fs";
import { buildMessages } from "../src/prompt.ts";
import { parsePreferenceRecords } from "../src/preferences.ts";

interface Variant { label: string; record: Record<string, string> | null; expect: Record<string, unknown> }
const { cases } = JSON.parse(readFileSync(new URL("../cases/cases.json", import.meta.url), "utf8")) as {
  cases: { id: string; question: string; variants: Variant[] }[];
};

let md = "# Recorded cases\n\nGenerated by `npm run record-cases`. The same question gets different instructions, and so different answers, depending on the preferences stored on the ENS name. Instructions are built only from app-authored text selected by validated values.\n";
for (const c of cases) {
  md += `\n## ${c.id}\n\n**Question (identical in every variant):** ${c.question}\n`;
  for (const v of c.variants) {
    const parsed = parsePreferenceRecords(v.record ?? {});
    const [system] = buildMessages(parsed.preferences, c.question);
    md += `\n### ${v.label}\n\n- ENS records: \`${JSON.stringify(v.record ?? {})}\`\n- Resolved (${parsed.source}${parsed.ignored.length ? `, ignored: ${parsed.ignored.join(", ")}` : ""}): \`${JSON.stringify(parsed.preferences)}\`\n- Expected property: \`${JSON.stringify(v.expect)}\`\n\nInstructions sent to the model:\n\n\`\`\`text\n${system!.content}\n\`\`\`\n`;
  }
}
writeFileSync(new URL("../cases/RECORDED.md", import.meta.url), md);
console.log("wrote cases/RECORDED.md");
